config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  devise_for :users

  root to: 'pages#home'

  resources :recipes
  resources :ingredients

  resources :meal_planner, only: [:index]

  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breakfast_recipe.rb
class BreakfastRecipe < ApplicationRecord
  belongs_to :day_meals
  belongs_to :user_meal

  has_many :day_meals
end

app/models/day_meal.rb
class DayMeal < ApplicationRecord
  belongs_to :meal_planner

  has_one :breakfast_recipe
  has_one :lunch_recipe
  has_one :dinner_recipe
end

app/models/dinner_recipe.rb
class DinnerRecipe < ApplicationRecord
  belongs_to :day_meals
  belongs_to :user_meal

  has_many :day_meals
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
end

app/models/lunch_recipe.rb
class LunchRecipe < ApplicationRecord
  belongs_to :day_meals
  belongs_to :user_meal

  has_many :day_meals
end

app/models/meal_planner.rb
class MealPlanner < ApplicationRecord
  has_many :day_meals
end

app/models/meeting.rb
class Meeting < ApplicationRecord


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipes
  belongs_to :ingredients
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :user_meals
end

app/models/user_meal.rb
class UserMeal < ApplicationRecord
  belongs_to :User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :set_time_zone, if: :user_signed_in?


  def after_sign_in_path_for(resource)
    recipes_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  # def set_time_zone
  #   Time.zone = current_user.time_zone
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:package_choice])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/meal_planner_controller.rb
class MealPlannerController < ApplicationController


  def index
    @show_navbar = true
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @show_navbar = true
    @recipes = Recipe.all
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @show_navbar = false
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @show_navbar = true
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to recipes_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to recipes_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :age, :weight, :sex, :height, :excercise, :main_meal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<div class="wrapper-calendar">
  <div class="container-calendar">

    <h1>Your Meal Plan</h1>
    <div class="add-recipe-container">

      <div>
        <p id="notice"><%= notice %></p>


        <h4>All our recipes:</h4>
        <div class="recipes-selection">
          <% @recipes.each do |recipe| %>
          <div id="my-draggable">
            <p>
              <%= recipe.name %>
            </p>
          </div>
          <% end %>
        </div>

      </div>

      <div class="container-monthly-calendar">
        <div>

            <div id="calendar">

            </div>

              <div>

              </div>

        </div>

      </div>

    </div>


  </div>
</div>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>

<h1><%= recipe.name %></h1>
<h2>Calories: <%=recipe.calories%> kcal</h2>
<h2>Fat:<%=recipe.fat%> g</h2>
<h2>Saturated Fat:<%=recipe.saturated_fat%> g</h2>
<h2>Carbs:<%=recipe.carbohydrates%> g</h2>
<% end %>

app/views/recipes/show.html.erb
<h1>Test</h1>

app/views/users/show.html.erb
<div class="container-fluid side-margin">
  <div class="row margin-left">
    <!-- LEFT SIDE -->
    <div class="col-xs-3 col-md-3 col-sm-3 sticky card-author-container">
      <div class="card-user">
          <div class="center">
            <img class="user-img">
          </div>
        <hr>
      </div>
        <div class="profile-options">
          <p><%= link_to "Followers", user_path(current_user) %></p>
          <p><%= link_to "Following", user_path(current_user) %></p>
          <p><%= link_to "Settings", user_path(current_user) %></p>
        </div>
    </div>

    <!-- RIGHT SIDE -->
    <div class="col-xs-8 col-md-8 col-sm-8 front">
      <div class="profile-page-right">
        <!-- User informations -->
        <h3><%= @user.email %></h3>
        <hr>
        <div>
          <h4>Age</h4>
          <p> <%= @user.age %></p>
        </div>
        <div>
          <hr>
          <h4>Sex</h4>
          <p> <%= @user.sex %></p>
        </div>
        <div>
          <hr>
          <h4>Weight</h4>
          <p><%= @user.weight %> Kg</p>
        </div>
        <hr>
        <div>
          <h4>Height</h4>
          <p> <%= @user.height %> cm</p>
        </div>
        <div>
          <hr>
          <h4>Excercise</h4>
          <p><%= @user.excercise %> times a week</p>
        </div>
        <hr>
        <div>
          <h4>Main meal</h4>
          <p> <%= @user.main_meal %></p>
        </div>
      </div>
    </div>
  </div>
</div>